name: Compile Mod
on:
  release:
    types:
      - created
  push:
  pull_request:

jobs:
  lint-and-compile:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2.1.0
      - name: Restore NuGet Packages
        run: nuget restore ${{ github.event.repository.name }}.sln
      - name: Patch csproj version
        uses: justalemon/VersionPatcher@v0.4
        with:
          version: 1.2.2.${{ github.run_number }}
          csproj-files: "**/**.csproj"
      - name: Compile
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: msbuild -m -p:Configuration=${{ matrix.configuration }} ${{ github.event.repository.name }}.sln
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.${{ matrix.configuration }}
          path: bin/${{ matrix.configuration }}
  deploy:
    runs-on: ubuntu-22.04
    #if: ${{ github.event_name == 'release' }}
    needs:
      - lint-and-compile
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1.0.6
      - name: Download the Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.Release
          path: bin/Release
      - name: List Everything
        run: ls -R
        working-directory: bin/Release
      - name: Repackage Files
        run: 7z a ${{ github.event.repository.name }}.zip ${{ env.GITHUB_WORKSPACE }}\bin\Release\*
      - name: Deploy NuGet
        if: ${{ github.event_name == 'release' }}
        run: nuget push bin/Release/FOR DEVELOPERS/*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET}}
